---
- name: dat ip cho loobpack
  hosts: all # tên của thiết bị trong Ansible server( vì ở đây chỉ có router nên có thể để all)
# các tác vụ
  tasks:
    - name: Set loopback IPv4 address # Đặt tên task để quản lý
      ios_l3_interface: # do cấu hình router nên bắt buộc khai báo như vậy
         name: loopback {{ item.number }} # tên cổng
         ipv4: 10.0.{{ item.name }}.1/24 # địa chỉ IP của loopback
        
        #int_id: "{{ item.number }}"
      #  name: "{{ item.name }}"
       # state: present
      with_items:
        - { number: 1, name: "10" }
        - { number: 2, name: "20" }
        - { number: 3, name: "30" }
  # - name: Show interface
   #   ios_command:
   #     commands:
  #        - show ip interface bri
  #    register: show_interface
      
   # - debug: var=show_interface.stdout_lines
